// Google Apps Script: doPost handler for receiving patient data and saving/updating to Google Sheets
function doPost(e) {
  try {
    // Parse incoming JSON data
    // My data is:
  /*   {
    "function": "doPost",
    "parameters": [
        [
            {
                "makp": "551",
                "tenkp": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "mabn": "2510000826",
                "hoten": "NGUYỄN VĂN TỚI",
                "ngaysinh": "1967-01-01T00:00:00",
                "namsinh": "1967",
                "phai": 0,
                "gioitinh": "Nam",
                "mavaovien": "250519092934726590",
                "maql": "250519092934726590",
                "idKhoa": "250521193450836696",
                "ngayvv": "19/05/2025 09:28",
                "ngayrv": null,
                "ngaydukienrv": "",
                "madoituong": 1,
                "doituong": "BHYT",
                "makpvv": "551",
                "tenkpvv": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "maicdvv": "I71",
                "chandoanvv": "Phình hình thoi động mạch chủ bụng dưới thận, phình động mạch chậu chung và chậu trong hai bên",
                "ngayvk": "21/05/2025 19:02",
                "tuoivao": "0580",
                "maicdvk": "I71",
                "chandoanvk": "Phình và tách thành động mạch chủ",
                "chandoanvk1": null,
                "mat": "",
                "maba": 11,
                "tenba": "Bệnh án ngoại khoa",
                "mabs": "7927",
                "dienthoai": "090****231",
                "cccd": "083067002757",
                "ngaydt": "0",
                "tenbs": "BS.CKI Bùi Trọng Đạt",
                "sdt": null,
                "sothe": "DK283832267389983106",
                "tungay": "01/01/2025 00:00:00",
                "denngay": "12/31/2025 00:00:00",
                "toanha": "e510f133e2356fb0e053020a14ac71e4",
                "mA_TOANHA": "C",
                "teN_TOANHA": "Tòa C",
                "tang": "e54a6ddf41885d6ae053020a14ac2eb0",
                "mA_TANG": "T2",
                "teN_TANG": "Tầng 2",
                "phong": "25967d141745c238e063620a0a0ac01a",
                "mA_PHONG": "P215",
                "teN_PHONG": "Phòng 215",
                "giuong": "25967d141748c238e063620a0a0ac01a",
                "mA_GIUONG": "G215-A",
                "teN_GIUONG": "G215-A",
                "tentt": "Tỉnh Bến Tre",
                "tenquan": "Huyện Ba Tri",
                "tenpxa": "Xã Bảo Thuận",
                "sonha": "152/TN Thạnh Ninh,",
                "cholam": "",
                "diachi": "152/TN Thạnh Ninh,,Xã Bảo Thuận - Huyện Ba Tri - Tỉnh Bến Tre",
                "lan": 0,
                "idseqkhamlai": 0,
                "checkuP_ID": null,
                "khamlai": 0,
                "phuongphappt": null,
                "mapppt": null,
                "ngaykham": null,
                "tenkhoachuyen": "KHOA GÂY MÊ - HỒI SỨC",
                "khoachuyen": "048",
                "sovaovien": "0013725/25",
                "ngaypt": null,
                "ngayvksort": "2025-05-21T19:02:00",
                "loaibn": 1,
                "todieutri": 1,
                "istienme": 0,
                "history": null,
                "coloR_STATUS": null,
                "noicapcccd": "",
                "ngaycapcccd": null,
                "nam": "0125+0425+0525+"
            },
            {
                "makp": "551",
                "tenkp": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "mabn": "2510128337",
                "hoten": "PHẠM THỊ LAN",
                "ngaysinh": "1975-07-03T00:00:00",
                "namsinh": "1975",
                "phai": 1,
                "gioitinh": "Nữ",
                "mavaovien": "250521055305082812",
                "maql": "250521132357293190",
                "idKhoa": "250521150322175649",
                "ngayvv": "21/05/2025 13:23",
                "ngayrv": null,
                "ngaydukienrv": "",
                "madoituong": 1,
                "doituong": "BHYT",
                "makpvv": "551",
                "tenkpvv": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "maicdvv": "D44.0",
                "chandoanvv": "U tân sinh không chắc chắn hoặc không biết tính chất của Tuyến giáp",
                "ngayvk": "21/05/2025 15:20",
                "tuoivao": "0500",
                "maicdvk": "D44.0",
                "chandoanvk": "Theo dõi K giáp thùy phải",
                "chandoanvk1": null,
                "mat": "",
                "maba": 1,
                "tenba": "Bệnh án nội khoa",
                "mabs": "4972",
                "dienthoai": "086****816",
                "cccd": "038175022614",
                "ngaydt": "1",
                "tenbs": "ThS.BS Phan Vũ Hồng Hải",
                "sdt": null,
                "sothe": "DK267672057649267015",
                "tungay": "01/01/2025 00:00:00",
                "denngay": "12/31/2025 00:00:00",
                "toanha": "e510f133e2356fb0e053020a14ac71e4",
                "mA_TOANHA": "C",
                "teN_TOANHA": "Tòa C",
                "tang": "e54a6ddf41895d6ae053020a14ac2eb0",
                "mA_TANG": "T3",
                "teN_TANG": "Tầng 3",
                "phong": "e5bd883083464ae9e053020a14ac31d9",
                "mA_PHONG": "P303",
                "teN_PHONG": "Phòng 303",
                "giuong": "e5bd883083f04ae9e053020a14ac31d9",
                "mA_GIUONG": "G303-A",
                "teN_GIUONG": "Giường A",
                "tentt": "Tỉnh Đắk Nông",
                "tenquan": "Huyện Đăk Glong",
                "tenpxa": "Xã Đắk Som",
                "sonha": "Bon B ` Nơr",
                "cholam": "",
                "diachi": "Bon B ` Nơr,Xã Đắk Som - Huyện Đăk Glong - Tỉnh Đắk Nông",
                "lan": 0,
                "idseqkhamlai": 0,
                "checkuP_ID": null,
                "khamlai": 0,
                "phuongphappt": null,
                "mapppt": null,
                "ngaykham": null,
                "tenkhoachuyen": "KHOA KHÁM BỆNH",
                "khoachuyen": "001",
                "sovaovien": "0014017/25",
                "ngaypt": null,
                "ngayvksort": "2025-05-21T15:20:00",
                "loaibn": 1,
                "todieutri": 1,
                "istienme": 1,
                "history": null,
                "coloR_STATUS": null,
                "noicapcccd": "",
                "ngaycapcccd": null,
                "nam": "0525+"
            },
            {
                "makp": "551",
                "tenkp": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "mabn": "2301298533",
                "hoten": "LÊ THỊ BÌNH",
                "ngaysinh": "1952-02-16T00:00:00",
                "namsinh": "1952",
                "phai": 1,
                "gioitinh": "Nữ",
                "mavaovien": "250520144926998921",
                "maql": "250520144926998921",
                "idKhoa": "250521151036087917",
                "ngayvv": "20/05/2025 14:48",
                "ngayrv": null,
                "ngaydukienrv": "",
                "madoituong": 1,
                "doituong": "BHYT",
                "makpvv": "551",
                "tenkpvv": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "maicdvv": "I87.2",
                "chandoanvv": "Suy tĩnh mạch hiển lớn hai bên",
                "ngayvk": "21/05/2025 15:00",
                "tuoivao": "0730",
                "maicdvk": "I87.2",
                "chandoanvk": "Suy tĩnh mạch (mạn) (ngoại biên)",
                "chandoanvk1": null,
                "mat": "",
                "maba": 1,
                "tenba": "Bệnh án nội khoa",
                "mabs": "4972",
                "dienthoai": "093****544",
                "cccd": "042152005307",
                "ngaydt": "0",
                "tenbs": "ThS.BS Phan Vũ Hồng Hải",
                "sdt": null,
                "sothe": "GD442421664458142008",
                "tungay": "01/20/2025 00:00:00",
                "denngay": "01/19/2026 00:00:00",
                "toanha": "e510f133e2356fb0e053020a14ac71e4",
                "mA_TOANHA": "C",
                "teN_TOANHA": "Tòa C",
                "tang": "e54a6ddf418a5d6ae053020a14ac2eb0",
                "mA_TANG": "T4",
                "teN_TANG": "Tầng 4",
                "phong": "e5bd8830836a4ae9e053020a14ac31d9",
                "mA_PHONG": "P414",
                "teN_PHONG": "Phòng 414",
                "giuong": "e5bd8830842e4ae9e053020a14ac31d9",
                "mA_GIUONG": "G414-A",
                "teN_GIUONG": "Giường A",
                "tentt": "Tỉnh Hà Tĩnh",
                "tenquan": "Huyện Lộc Hà",
                "tenpxa": "Thị Trấn Lộc Hà",
                "sonha": "Thị Trấn Lộc Hà",
                "cholam": "",
                "diachi": "Thị Trấn Lộc Hà,Thị Trấn Lộc Hà - Huyện Lộc Hà - Tỉnh Hà Tĩnh",
                "lan": 0,
                "idseqkhamlai": 0,
                "checkuP_ID": null,
                "khamlai": 0,
                "phuongphappt": null,
                "mapppt": null,
                "ngaykham": null,
                "tenkhoachuyen": "KHOA GÂY MÊ - HỒI SỨC",
                "khoachuyen": "048",
                "sovaovien": "0013902/25",
                "ngaypt": null,
                "ngayvksort": "2025-05-21T15:00:00",
                "loaibn": 1,
                "todieutri": 1,
                "istienme": 0,
                "history": null,
                "coloR_STATUS": null,
                "noicapcccd": "",
                "ngaycapcccd": null,
                "nam": "1223+0124+0525+"
            },
            {
                "makp": "551",
                "tenkp": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "mabn": "2301300393",
                "hoten": "TĂNG HỮU HẠNH",
                "ngaysinh": "1963-01-01T00:00:00",
                "namsinh": "1963",
                "phai": 1,
                "gioitinh": "Nữ",
                "mavaovien": "250521084606577000",
                "maql": "250521111459635768",
                "idKhoa": "250521131143012853",
                "ngayvv": "21/05/2025 11:14",
                "ngayrv": null,
                "ngaydukienrv": "",
                "madoituong": 1,
                "doituong": "BHYT",
                "makpvv": "551",
                "tenkpvv": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "maicdvv": "I87.2",
                "chandoanvv": "Suy tĩnh mạch (mạn) (ngoại biên)",
                "ngayvk": "21/05/2025 13:10",
                "tuoivao": "0620",
                "maicdvk": "L03.1",
                "chandoanvk": "Viêm mô bào ở các phần khác của chi",
                "chandoanvk1": null,
                "mat": "",
                "maba": 11,
                "tenba": "Bệnh án ngoại khoa",
                "mabs": "9725",
                "dienthoai": "093****258",
                "cccd": "091163006671",
                "ngaydt": "1",
                "tenbs": "ThS.BSNT.CKI Phạm Hưng",
                "sdt": null,
                "sothe": "XD291912307870091355",
                "tungay": "01/01/2025 00:00:00",
                "denngay": "12/31/2025 00:00:00",
                "toanha": "e510f133e2356fb0e053020a14ac71e4",
                "mA_TOANHA": "C",
                "teN_TOANHA": "Tòa C",
                "tang": "e54a6ddf418a5d6ae053020a14ac2eb0",
                "mA_TANG": "T4",
                "teN_TANG": "Tầng 4",
                "phong": "e83c4997468e0746e053020a14ace9d0",
                "mA_PHONG": "P410",
                "teN_PHONG": "Phòng 410",
                "giuong": "e83d168f21ae1a92e053020a14ac0930",
                "mA_GIUONG": "G410-A",
                "teN_GIUONG": "Giường A",
                "tentt": "Tỉnh Kiên Giang",
                "tenquan": "Thành phố Phú Quốc",
                "tenpxa": "Xã Cửa Dương",
                "sonha": "Ấp Ông Lang",
                "cholam": "",
                "diachi": "Ấp Ông Lang,Xã Cửa Dương - Thành phố Phú Quốc - Tỉnh Kiên Giang",
                "lan": 0,
                "idseqkhamlai": 0,
                "checkuP_ID": null,
                "khamlai": 0,
                "phuongphappt": null,
                "mapppt": null,
                "ngaykham": null,
                "tenkhoachuyen": "KHOA KHÁM BỆNH",
                "khoachuyen": "001",
                "sovaovien": "0014000/25",
                "ngaypt": null,
                "ngayvksort": "2025-05-21T13:10:00",
                "loaibn": 1,
                "todieutri": 1,
                "istienme": 0,
                "history": null,
                "coloR_STATUS": null,
                "noicapcccd": "",
                "ngaycapcccd": null,
                "nam": "1223+0124+0524+0624+0724+0924+0525+"
            },
            {
                "makp": "551",
                "tenkp": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "mabn": "2510069821",
                "hoten": "NGUYỄN HIẾU THUẬN",
                "ngaysinh": "2005-01-17T00:00:00",
                "namsinh": "2005",
                "phai": 0,
                "gioitinh": "Nam",
                "mavaovien": "250519092129254590",
                "maql": "250519092129254590",
                "idKhoa": "250520155212231363",
                "ngayvv": "19/05/2025 09:18",
                "ngayrv": null,
                "ngaydukienrv": "",
                "madoituong": 2,
                "doituong": "Thu phí",
                "makpvv": "551",
                "tenkpvv": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "maicdvv": "Q67.6",
                "chandoanvv": "Lõm ngực lệch tâm dạng phẳng HI#3",
                "ngayvk": "20/05/2025 15:30",
                "tuoivao": "0200",
                "maicdvk": "Q67.6",
                "chandoanvk": "Lõm ngực lệch tâm dạng phẳng HI#3",
                "chandoanvk1": null,
                "mat": "",
                "maba": 11,
                "tenba": "Bệnh án ngoại khoa",
                "mabs": "4972",
                "dienthoai": "038****243",
                "cccd": "086205005297",
                "ngaydt": "1",
                "tenbs": "ThS.BS Phan Vũ Hồng Hải",
                "sdt": null,
                "sothe": "",
                "tungay": "",
                "denngay": "",
                "toanha": "e510f133e2356fb0e053020a14ac71e4",
                "mA_TOANHA": "C",
                "teN_TOANHA": "Tòa C",
                "tang": "e54a6ddf41885d6ae053020a14ac2eb0",
                "mA_TANG": "T2",
                "teN_TANG": "Tầng 2",
                "phong": "25967d141744c238e063620a0a0ac01a",
                "mA_PHONG": "P214",
                "teN_PHONG": "Phòng 214",
                "giuong": "25967d141747c238e063620a0a0ac01a",
                "mA_GIUONG": "G214-A",
                "teN_GIUONG": "Giường A",
                "tentt": "Tỉnh Vĩnh Long",
                "tenquan": "Huyện Tam Bình",
                "tenpxa": "Xã Hoà Hiệp",
                "sonha": "Tổ 8 Ấp 8",
                "cholam": "",
                "diachi": "Tổ 8 Ấp 8,Xã Hoà Hiệp - Huyện Tam Bình - Tỉnh Vĩnh Long",
                "lan": 0,
                "idseqkhamlai": 0,
                "checkuP_ID": null,
                "khamlai": 0,
                "phuongphappt": null,
                "mapppt": null,
                "ngaykham": null,
                "tenkhoachuyen": "KHOA GÂY MÊ - HỒI SỨC",
                "khoachuyen": "048",
                "sovaovien": "0013723/25",
                "ngaypt": null,
                "ngayvksort": "2025-05-20T15:30:00",
                "loaibn": 1,
                "todieutri": 1,
                "istienme": 0,
                "history": null,
                "coloR_STATUS": null,
                "noicapcccd": "",
                "ngaycapcccd": null,
                "nam": "0325+0525+"
            },
            {
                "makp": "551",
                "tenkp": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "mabn": "2510100609",
                "hoten": "ĐẶNG THỊ GIÁM",
                "ngaysinh": "1948-10-19T00:00:00",
                "namsinh": "1948",
                "phai": 1,
                "gioitinh": "Nữ",
                "mavaovien": "250514090102231194",
                "maql": "250514130349519068",
                "idKhoa": "250519095421204208",
                "ngayvv": "14/05/2025 09:30",
                "ngayrv": null,
                "ngaydukienrv": "",
                "madoituong": 1,
                "doituong": "BHYT",
                "makpvv": "551",
                "tenkpvv": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "maicdvv": "J90",
                "chandoanvv": "Tràn dịch màng phổi trái lượng nhiều",
                "ngayvk": "19/05/2025 09:30",
                "tuoivao": "0770",
                "maicdvk": "J90",
                "chandoanvk": "Tràn dịch màng phổi trái lượng nhiều",
                "chandoanvk1": null,
                "mat": "",
                "maba": 11,
                "tenba": "Bệnh án ngoại khoa",
                "mabs": "2670",
                "dienthoai": "090****286",
                "cccd": "051148000658",
                "ngaydt": "2",
                "tenbs": "ThS.BS.CKI Lê Thị Ngọc Hằng",
                "sdt": null,
                "sothe": "GD467672101296267014",
                "tungay": "05/26/2024 00:00:00",
                "denngay": "05/25/2025 00:00:00",
                "toanha": "e510f133e2356fb0e053020a14ac71e4",
                "mA_TOANHA": "C",
                "teN_TOANHA": "Tòa C",
                "tang": "e54a6ddf41885d6ae053020a14ac2eb0",
                "mA_TANG": "T2",
                "teN_TANG": "Tầng 2",
                "phong": "25967d141746c238e063620a0a0ac01a",
                "mA_PHONG": "P216",
                "teN_PHONG": "Phòng 216",
                "giuong": "25967d14174dc238e063620a0a0ac01a",
                "mA_GIUONG": "G216-B",
                "teN_GIUONG": "G216-B",
                "tentt": "Tỉnh Đắk Nông",
                "tenquan": "Huyện Đắk R'Lấp",
                "tenpxa": "Xã Kiến Thành",
                "sonha": "THÔN 6 ",
                "cholam": "",
                "diachi": "THÔN 6,Xã Kiến Thành - Huyện Đắk R'Lấp - Tỉnh Đắk Nông",
                "lan": 0,
                "idseqkhamlai": 0,
                "checkuP_ID": null,
                "khamlai": 0,
                "phuongphappt": null,
                "mapppt": null,
                "ngaykham": null,
                "tenkhoachuyen": "KHOA GÂY MÊ - HỒI SỨC",
                "khoachuyen": "048",
                "sovaovien": "0013225/25",
                "ngaypt": null,
                "ngayvksort": "2025-05-19T09:30:00",
                "loaibn": 1,
                "todieutri": 1,
                "istienme": 0,
                "history": null,
                "coloR_STATUS": null,
                "noicapcccd": "",
                "ngaycapcccd": null,
                "nam": "0425+0525+"
            },
            {
                "makp": "551",
                "tenkp": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "mabn": "2510122316",
                "hoten": "NGUYỄN VĂN CÁT",
                "ngaysinh": "1962-01-12T00:00:00",
                "namsinh": "1962",
                "phai": 0,
                "gioitinh": "Nam",
                "mavaovien": "250512074816418718",
                "maql": "250512114635514700",
                "idKhoa": "250517165114581312",
                "ngayvv": "12/05/2025 07:46",
                "ngayrv": null,
                "ngaydukienrv": "",
                "madoituong": 1,
                "doituong": "BHYT",
                "makpvv": "551",
                "tenkpvv": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "maicdvv": "D14.3",
                "chandoanvv": "U thùy trên phổi phải",
                "ngayvk": "17/05/2025 16:39",
                "tuoivao": "0630",
                "maicdvk": "D38.1",
                "chandoanvk": "U thùy trên phổi phải",
                "chandoanvk1": null,
                "mat": "",
                "maba": 11,
                "tenba": "Bệnh án ngoại khoa",
                "mabs": "9725",
                "dienthoai": "098****465",
                "cccd": "038062012676",
                "ngaydt": "4",
                "tenbs": "ThS.BSNT.CKI Phạm Hưng",
                "sdt": null,
                "sothe": "HT375479706395075096",
                "tungay": "02/01/2025 00:00:00",
                "denngay": "12/31/2025 00:00:00",
                "toanha": "e510f133e2356fb0e053020a14ac71e4",
                "mA_TOANHA": "C",
                "teN_TOANHA": "Tòa C",
                "tang": "e54a6ddf41885d6ae053020a14ac2eb0",
                "mA_TANG": "T2",
                "teN_TANG": "Tầng 2",
                "phong": "25967d141745c238e063620a0a0ac01a",
                "mA_PHONG": "P215",
                "teN_PHONG": "Phòng 215",
                "giuong": "25967d141749c238e063620a0a0ac01a",
                "mA_GIUONG": "G215-B",
                "teN_GIUONG": "G215-B",
                "tentt": "Tỉnh Đồng Nai",
                "tenquan": "Huyện Cẩm Mỹ",
                "tenpxa": "Xã Sông Ray",
                "sonha": "tổ 3,ấp 5",
                "cholam": "",
                "diachi": "tổ 3,ấp 5,Xã Sông Ray - Huyện Cẩm Mỹ - Tỉnh Đồng Nai",
                "lan": 0,
                "idseqkhamlai": 0,
                "checkuP_ID": null,
                "khamlai": 0,
                "phuongphappt": null,
                "mapppt": null,
                "ngaykham": null,
                "tenkhoachuyen": "KHOA GÂY MÊ - HỒI SỨC",
                "khoachuyen": "048",
                "sovaovien": "0012940/25",
                "ngaypt": null,
                "ngayvksort": "2025-05-17T16:39:00",
                "loaibn": 1,
                "todieutri": 1,
                "istienme": 0,
                "history": null,
                "coloR_STATUS": null,
                "noicapcccd": "",
                "ngaycapcccd": null,
                "nam": "0525+"
            },
            {
                "makp": "551",
                "tenkp": "KHOA NGOẠI LỒNG NGỰC - MẠCH MÁU",
                "mabn": "2510120493",
                "hoten": "PHAN THỊ LY",
                "ngaysinh": "1993-12-17T00:00:00",
                "namsinh": "1993",
                "phai": 1,
                "gioitinh": "Nữ",
                "mavaovien": "250509142853244773",
                "maql": "250509161814910910",
                "idKhoa": "250517093222406010",
                "ngayvv": "09/05/2025 14:26",
                "ngayrv": null,
                "ngaydukienrv": "",
                "madoituong": 1,
                "doituong": "BHYT",
                "makpvv": "057",
                "tenkpvv": "KHOA NỘI TỔNG HỢP",
                "maicdvv": "J15.8",
                "chandoanvv": "Theo dõi kén khí ở phổi bội nhiễm",
                "ngayvk": "16/05/2025 17:57",
                "tuoivao": "0320",
                "maicdvk": "J15.8",
                "chandoanvk": "Theo dõi kén khí ở phổi bội nhiễm",
                "chandoanvk1": null,
                "mat": "",
                "maba": 11,
                "tenba": "Bệnh án ngoại khoa",
                "mabs": "9725",
                "dienthoai": "097****123",
                "cccd": "042193017318",
                "ngaydt": "5",
                "tenbs": "ThS.BSNT.CKI Phạm Hưng",
                "sdt": null,
                "sothe": "DN479422129252475250",
                "tungay": "01/01/2025 00:00:00",
                "denngay": "12/31/2025 00:00:00",
                "toanha": "e510f133e2356fb0e053020a14ac71e4",
                "mA_TOANHA": "C",
                "teN_TOANHA": "Tòa C",
                "tang": "e54a6ddf41885d6ae053020a14ac2eb0",
                "mA_TANG": "T2",
                "teN_TANG": "Tầng 2",
                "phong": "25967d141746c238e063620a0a0ac01a",
                "mA_PHONG": "P216",
                "teN_PHONG": "Phòng 216",
                "giuong": "25967d14174cc238e063620a0a0ac01a",
                "mA_GIUONG": "G216-A",
                "teN_GIUONG": "G216-A",
                "tentt": "Tỉnh Đồng Nai",
                "tenquan": "Thành phố Biên Hòa",
                "tenpxa": "Phường Phước Tân",
                "sonha": "KP Vườn Dừa",
                "cholam": "",
                "diachi": "KP Vườn Dừa,Phường Phước Tân - Thành phố Biên Hòa - Tỉnh Đồng Nai",
                "lan": 0,
                "idseqkhamlai": 0,
                "checkuP_ID": null,
                "khamlai": 0,
                "phuongphappt": null,
                "mapppt": null,
                "ngaykham": null,
                "tenkhoachuyen": "KHOA GÂY MÊ - HỒI SỨC",
                "khoachuyen": "048",
                "sovaovien": "0012673/25",
                "ngaypt": null,
                "ngayvksort": "2025-05-16T17:57:00",
                "loaibn": 1,
                "todieutri": 1,
                "istienme": 0,
                "history": null,
                "coloR_STATUS": null,
                "noicapcccd": "",
                "ngaycapcccd": null,
                "nam": "0525+"
            }
        ]
    ]
} */
    var data = JSON.parse(e.postData.contents);
    // Extract patient array from the expected structure
    if (!data || !Array.isArray(data.parameters) || !Array.isArray(data.parameters[0])) {
      throw new Error('Invalid data format');
    }
    data = data.parameters[0];
    // Open the sheet named "DanhSachBN" in the active spreadsheet
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("DanhSachBN");
    if (!sheet) {
      throw new Error('Sheet "DanhSachBN" not found');
    }
    // Prepare header row (if not present)
    var headers = [
      'Mã khoa', 'Tên khoa', 'Mã bệnh nhân', 'Họ tên', 'Ngày sinh', 'Năm sinh', 'Giới tính',
      'Mã khám bệnh', 'Ngày vào viện', 'Mã đối tượng', 'Đối tượng', 'Ngày vào khoa',
      'Mã ICD vào khoa', 'Chẩn đoán vào khoa', 'Tên tòa nhà', 'Tên tầng',
     'Tên phòng', 'Tên giường'
    ];
    if (sheet.getLastRow() === 0) {
      sheet.appendRow(headers);
    }
    var mabnCol = 3; // 'Mã bệnh nhân' is the 3rd column (1-based)
    var lastRow = sheet.getLastRow();
    var mabnMap = {};
    if (lastRow > 1) {
      var mabnValues = sheet.getRange(2, mabnCol, lastRow - 1, 1).getValues();
      for (var i = 0; i < mabnValues.length; i++) {
        mabnMap[mabnValues[i][0]] = i + 2; // row number in sheet
      }
    }
    var updated = 0, inserted = 0;
    // Map and append or update each patient row
    data.forEach(function(item) {
      var row = [
        item.makp || '',
        item.tenkp || '',
        item.mabn || '',
        item.hoten || '',
        item.ngaysinh || '',
        item.namsinh || '',
        item.gioitinh || '',
        item.mavaovien || '',
        item.ngayvv || '',
        item.madoituong || '',
        item.doituong || '',
        item.ngayvk || '',
        item.maicdvk || '',
        item.chandoanvk || '',
        item.teN_TOANHA || '',
        item.teN_TANG || '',
        item.teN_PHONG || '',
        item.teN_GIUONG || ''
      ];
      var mabn = item.mabn || '';
      if (mabn && mabnMap[mabn]) {
        // Update existing row
        sheet.getRange(mabnMap[mabn], 1, 1, row.length).setValues([row]);
        updated++;
      } else {
        // Insert new row
        sheet.appendRow(row);
        inserted++;
      }
    });
    return ContentService.createTextOutput(JSON.stringify({status: 'success', updated: updated, inserted: inserted})).setMimeType(ContentService.MimeType.JSON);
  } catch (err) {
    return ContentService.createTextOutput(JSON.stringify({status: 'error', message: err.message})).setMimeType(ContentService.MimeType.JSON);
  }
}
